/**
 * Every Material Symbols icon the UI can render.
 *
 * The bundled icon font (`public/fonts/`) is subset to exactly this list — the full
 * variable font is 3.8 MB, this subset is a fraction of that. An icon that is used in a
 * component but missing here has no glyph and renders as its raw ligature text
 * (the literal word "settings" instead of a gear).
 *
 * `npm run build-fonts` regenerates the font files from this list.
 * `src/test/__tests__/icon-manifest.test.ts` fails the build if a component references
 * an icon that is not listed here, so this cannot silently drift.
 */
export const ICON_MANIFEST = [
  'account_tree',
  'add',
  'add_circle',
  'api',
  'architecture',
  'arrow_back',
  'arrow_forward',
  'article',
  'bar_chart',
  'bug_report',
  'cancel',
  'celebration',
  'chat',
  'check',
  'check_box_outline_blank',
  'check_circle',
  'chevron_left',
  'chevron_right',
  'close',
  'cloud',
  'cloud_done',
  'cloud_off',
  'cloud_sync',
  'code',
  'code_blocks',
  'code_off',
  'css',
  'dashboard',
  'database',
  'delete',
  'description',
  'desktop_windows',
  'difference',
  'dns',
  'download',
  'edit',
  'edit_note',
  'emoji_events',
  'error',
  'expand_less',
  'expand_more',
  'filter_alt',
  'fitness_center',
  'folder',
  'folder_open',
  'handyman',
  'help',
  'hourglass_top',
  'html',
  'hub',
  'image',
  'info',
  'inventory_2',
  'javascript',
  'key',
  'keyboard',
  'left_panel_close',
  'left_panel_open',
  'lightbulb',
  'link',
  'lock',
  'lock_open',
  'map',
  'memory',
  'menu_book',
  'note_add',
  'notifications',
  'open_in_new',
  'output',
  'palette',
  'person',
  'play_arrow',
  'play_circle',
  'progress_activity',
  'psychology',
  'refresh',
  'remove',
  'rocket_launch',
  'route',
  'router',
  'school',
  'search',
  'search_off',
  'send',
  'settings',
  'settings_ethernet',
  'smart_toy',
  'source',
  'table_chart',
  'terminal',
  'token',
  'touch_app',
  'trending_flat',
  'tune',
  'undo',
  'upload',
  'verified',
  'verified_user',
  'warning',
  'waving_hand',
  'web',
  'widgets',
] as const;

export type IconName = (typeof ICON_MANIFEST)[number];

/** Fast membership check for the manifest guard test. */
export const ICON_SET: ReadonlySet<string> = new Set(ICON_MANIFEST);
