/**
 * Downloads and self-hosts every webfont the IDE uses into `public/fonts/`.
 *
 * Why this exists: the app previously loaded Space Grotesk, JetBrains Mono, and
 * Material Symbols from fonts.googleapis.com at runtime. A packaged desktop app is
 * routinely used offline, and when that request failed every one of the app's icons
 * rendered as its raw ligature text ("settings", "cloud_off", "account_tree") and the
 * whole type system fell back to system defaults. Bundling makes the UI deterministic
 * and drops a third-party request from startup.
 *
 * The icon font is subset to `src/config/iconManifest.ts` — the full variable font is
 * 3.8 MB, which is not worth shipping for ~95 glyphs.
 *
 * Run: npm run build-fonts
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = path.join(ROOT, 'public', 'fonts');
const MANIFEST = path.join(ROOT, 'src', 'config', 'iconManifest.ts');

// A desktop Chrome UA makes the API serve woff2, which is the smallest format and is
// universally supported by the Chromium version bundled with Electron.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

async function readIconNames() {
  const src = await fs.readFile(MANIFEST, 'utf8');
  const block = src.match(/ICON_MANIFEST\s*=\s*\[([\s\S]*?)\]\s*as const/);
  if (!block) throw new Error('Could not parse ICON_MANIFEST from src/config/iconManifest.ts');
  const names = [...block[1].matchAll(/'([a-z0-9_]+)'/g)].map((m) => m[1]);
  if (!names.length) throw new Error('ICON_MANIFEST is empty');
  return names;
}

async function fetchCss(url, label) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`CSS fetch failed for ${label}: ${res.status} ${res.statusText}`);
  return res.text();
}

/** Downloads every gstatic font referenced by `css` and rewrites it to local /fonts/ paths. */
async function localize(css, label) {
  const urls = [...new Set([...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map((m) => m[1]))];
  if (!urls.length) throw new Error(`No font files referenced in ${label} CSS`);

  let bytes = 0;
  for (const url of urls) {
    // Static families come from /s/<family>/<v>/<hash>.woff2, but a subset request returns
    // /l/font?kit=...&skey=..., which is not a usable filename. Derive a stable name from a
    // hash of the URL instead, so both shapes work and re-runs stay deterministic.
    const family = (url.split('/')[4] || '').match(/^[a-z0-9]+/)?.[0] || label;
    const local = `${family}-${createHash('sha1').update(url).digest('hex').slice(0, 12)}.woff2`;

    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`Font download failed: ${url} -> ${res.status}`);
    const buf = Buffer.from(await res.arrayBuffer());
    await fs.writeFile(path.join(FONT_DIR, local), buf);
    bytes += buf.length;

    css = css.split(url).join(`/fonts/${local}`);
  }
  console.log(`  ${label}: ${urls.length} file(s), ${(bytes / 1024).toFixed(0)} KB`);
  return css;
}

const iconNames = await readIconNames();
console.log(`Building fonts (${iconNames.length} icons in manifest)...`);

await fs.rm(FONT_DIR, { recursive: true, force: true });
await fs.mkdir(FONT_DIR, { recursive: true });

const textCss = await localize(
  await fetchCss(
    'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap',
    'text'
  ),
  'text'
);

// `icon_names` makes the API return a font subset to just these glyphs.
const iconCss = await localize(
  await fetchCss(
    'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200' +
      `&icon_names=${iconNames.join(',')}&display=block`,
    'icons'
  ),
  'icons'
);

const out = `/*
 * GENERATED by scripts/build-fonts.mjs — do not edit by hand.
 * Run \`npm run build-fonts\` to regenerate after changing src/config/iconManifest.ts.
 */

${textCss}
${iconCss}
`;

await fs.writeFile(path.join(FONT_DIR, 'fonts.css'), out, 'utf8');

const files = await fs.readdir(FONT_DIR);
let total = 0;
for (const f of files) total += (await fs.stat(path.join(FONT_DIR, f))).size;
console.log(`Wrote ${files.length} files to public/fonts/ — ${(total / 1024).toFixed(0)} KB total`);
